### PR TITLE
Advance to dropwizard-0.8.0.

### PR DESCRIPTION
**Pull request by tedsharpe**
This isn't an emergency, but if someone had a minute to look at this, that would be great.

### CODE REVIEW

**Comment by rushtong** [comment]
Unrelated to this PR, but boss-ws.pom still has an oracle profile (biofortisdb) that isn't valid anymore.

**Comment by rushtong** [comment]
I am curious about the removal of the @ApiModelProperty dataType properties. Were there issues there?

**Comment by tedsharpe** [comment]
Yes, on the dataType properties.  I was getting errors with "URI" and "String[]" for some reason.  If it messes up the swagger pages I'll have to try to figure it out, but I assumed that the dataType would default to the actual Java type of the property.  Not so?
I removed that dead oracle profile -- thanks.

**Comment by rushtong** [comment]
As per the javadoc - it does default to what it can find from the actual class property. 
Love the Response & readEntity refactoring.
Looks good - will merge (after rebase/squash if needed) - just let me know.

**Comment by tedsharpe** [comment]
Response and readEntity:  That's Jersey 2.  Easy to use.
I'll probably dink with the swagger a little:  it's still a bit rough.  Then I'll squash and let you take a look and merge.
Thanks very much for having a look.

**Pull request merged**
